# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 1200s
options:
  substitution_option: ALLOW_LOOSE
  machineType: 'N1_HIGHCPU_8'

# Execution environment:
# HOME=/builder/home
# pwd=/workspace
# BUILDER_OUTPUT=/builder/outputs
# GOCACHE=/gocache


steps:

  # Build golden base, hgate, test app using Kaniko.
  # ~2 min
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: base-kaniko
    args:
      - --destination=gcr.io/$PROJECT_ID/krun:$BRANCH_NAME
      - --cache=true
      - --cache-ttl=240h
      - --force
    timeout: 1200s

  # ~15sec
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: fortio
    args:
      - --destination=gcr.io/$PROJECT_ID/fortio-mesh:$BRANCH_NAME
      - --dockerfile=samples/fortio/Dockerfile
      - --context=dir://samples/fortio
      - --build-arg=BASE=gcr.io/$PROJECT_ID/krun:$BRANCH_NAME
      - --cache=true
      - --cache-ttl=240h
    timeout: 1200s
    waitFor:
      - base-kaniko

  - name: 'gcr.io/kaniko-project/executor:latest'
    id: hgate
    args:
      - --destination=gcr.io/$PROJECT_ID/hgate:$BRANCH_NAME
      - --dockerfile=cmd/gate/Dockerfile
      - --build-arg=BASE=gcr.io/$PROJECT_ID/krun:$BRANCH_NAME
      - --cache=true
      - --cache-ttl=240h
    timeout: 1200s
    waitFor:
      - base-kaniko

  # Run tests. We need a docker image with cloudrun (for get credentials).
  #  gcloud get-credentials generate a KUBECONFIG file using exec gcloud - so it must be present.
  - name: gcr.io/wlhe-cr/gcloud-alpha
    entrypoint: /bin/sh
    env:
      - PROJECT_ID=$PROJECT_ID
      - CLUSTER_NAME=asm-cr
      - CLUSTER_LOCATION=us-central1-c
      - FORTIO_IMAGE=gcr.io/$PROJECT_ID/fortio-mesh:$BRANCH_NAME
      - KUBECONFIG=/workspace/kubeconfig
    waitFor:
      - "-"
    args:
      - -c
      - |
        gcloud container clusters get-credentials asm-cr --zone us-central1-c --project $PROJECT_ID
        make test

  # Deploy the in-cluster connector. Note that the runner doesn't have RBAC permissions
  # The cluster must be setup with the RBAC manually.
  - name: gcr.io/wlhe-cr/gcloud-alpha
    id: hgatedeploy
    entrypoint: /bin/sh
    env:
      - PROJECT_ID=$PROJECT_ID
      - CLUSTER_NAME=asm-cr
      - CLUSTER_LOCATION=us-central1-c
      - FORTIO_IMAGE=gcr.io/$PROJECT_ID/fortio-mesh:$BRANCH_NAME
      - KUBECONFIG=/workspace/kubeconfig
    waitFor:
      - hgate
    args:
      - -c
      - |
        make deploy/hgate

  # Deploy the canary, run tests
  # Missing alpha command in 'gcr.io/google.com/cloudsdktool/cloud-sdk', also too large.
  # This is built with 'make gcp/builder-gcloud', alpine based.
  - name: gcr.io/wlhe-cr/gcloud-alpha
    entrypoint: /bin/sh
    env:
      - PROJECT_ID=$PROJECT_ID
      - CLUSTER_NAME=asm-cr
      - CLUSTER_LOCATION=us-central1-c
      - FORTIO_IMAGE=gcr.io/$PROJECT_ID/fortio-mesh:$BRANCH_NAME
      - KUBECONFIG=/workspace/kubeconfig
    waitFor:
      - fortio
      - hgatedeploy
    args:
      - -c
      - |
        make canary

  # TODO: combine gcloud, go, etc in single image - Istio build image is huge
  # Also includes gcloud 349.0.0
  # https://github.com/GoogleCloudPlatform/cloud-builders-community/tree/master/ko is a good
  # base, includes ko, kubectl, gcloud
  # They use: CLOUDSDK_COMPUTE_ZONE, CLOUDSDK_CONTAINER_CLUSTER, CLOUDSDK_CORE_PROJECT
#go get -u github.com/jstemmer/go-junit-report
#2>&1 go test -timeout 1m -v ./... | tee sponge.log
#/go/bin/go-junit-report -set-exit-code < sponge.log > ${SHORT_SHA}_test_log.xml



