# gcloud builds submit . --config=cloudbuild.yaml
substitutions:
  _KO_GIT_TAG: 'main'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'KO_GIT_TAG=${_KO_GIT_TAG}', '--tag=gcr.io/$PROJECT_ID/gcloud-alpha', '-f', 'tools/gcloud-alpha/Dockerfile', '.']

images: ['gcr.io/$PROJECT_ID/gcloud-alpha']
