# gcloud builds submit . --config=cloudbuild.yaml
substitutions:
  _KO_GIT_TAG: 'main'
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--build-arg', 'KO_GIT_TAG=${_KO_GIT_TAG}', '--tag=gcr.io/$PROJECT_ID/ko', '-f', 'tools/ko/Dockerfile', '.']

images: ['gcr.io/$PROJECT_ID/ko']
