# Dockerfile using an external build (similar with Istio)

ARG BASE=gcr.io/istio-testing/proxyv2:latest

FROM ${BASE}

COPY krun /usr/local/bin/krun
COPY bootstrap_template.yaml /td_resources/
COPY iptables.sh /td_resources/

WORKDIR /

ENTRYPOINT ["/usr/local/bin/krun"]
