# Dockerfile using an external build (similar with Istio)

ARG BASE=gcr.io/istio-testing/proxyv2:1.13-dev

FROM ${BASE}

COPY krun /usr/local/bin/krun
COPY bootstrap_template.yaml /td_resources/
COPY iptables.sh /td_resources/

WORKDIR /
USER 0

# Add a version variant, since this is different enough in packaging.
ENV ISTIO_META_ISTIO_VERSION 1.13-master-cloudrun
RUN /usr/local/bin/envoy --version
ENTRYPOINT ["/usr/local/bin/krun"]
