# Dockerfile using an external build (similar with Istio)

ARG BASE=gcr.io/istio-testing/proxyv2:latest

FROM ${BASE}

COPY krun /usr/local/bin/krun
COPY bootstrap_template.yaml /td_resources/
COPY iptables.sh /td_resources/

WORKDIR /
USER 0

# Add a version variant, since this is different enough in packaging.
ENV ISTIO_META_ISTIO_VERSION 1.13-master-cloudrun

ENTRYPOINT ["/usr/local/bin/krun"]
